### ISSUE TITLE
Memory leak by not clearing $rootScope.$on('$viewContentLoaded') listener

### ISSUE THREAD

**Issue by ionutmandra** [ncuillery/angular-breadcrumb#98] opened 2015-07-14 05:07 UTC
Hi,

There are 2 or 3 places that use ````$rootScope.$on('$viewContentLoaded')````, wihout actually clearing the listener in scope destroy method. I had a test only for  ````$rootScope.$on('$viewContentLoaded', function () { renderBreadcrumb();});````. Because the rootScope is never destroyed, it keeps it's renderBreadcrumb listener, having some scopes as context variables. So navigating through multiple views, on rootScope such listeners would add and the scopes that we use for the components, together with their data and elements, will remain stuck with those closures.

For the moment I had just a test like 
````var unregister = $rootScope.$on('$viewContentLoaded', function () {  renderBreadcrumb(); });````

````function handleDestroyEvent() { unregister(); } ````

```` scope.$on("$destroy",handleDestroyEvent); ````

Checking the heap with Chrome profiling, it seems to release the scopes.

**Comment by c-ice** [comment] 2015-08-03 09:26
+1

**Comment by ncuillery** [comment] 2015-09-17 12:09
Thanks for the report and the fix suggestion.

**Comment by ronaldheft** [comment] 2016-03-01 16:05
I was burned pretty badly in my application due to this memory leak. The root cause is actually multiple event listeners get registered on every $stateChange, and then the memory is never released in addition to firing the function an additional time for every $stateChange.

I resolved this in #134 by deregistering the listener when the same listener is registered again using a simple tagging method. A better solution would be to truly only register the listeners once by refactoring where the listener are registered, since $rootScope only exists once in the application anyway. Regardless, this solution will get the job done.

**Closed** 2016-04-11 15:30 UTC
Labels: answered, pr welcome
